SELECT REVIEW_ID,
       ORDER_ID,
       REVIEW_SCORE,
       Case WHEN REVIEW_COMMENT_TITLE is null THEN 'N/A' END as REVIEW_COMMENT_TITLE,
       Case WHEN REVIEW_COMMENT_MESSAGE is null THEN 'N/A' END as REVIEW_COMMENT_MESSAGE,
       REVIEW_CREATION_DATE,
       REVIEW_ANSWER_TIMESTAMP
FROM {{source("olist_source","order_reviews")}}